---
# Sample hosts configuration file
# Replace with your actual network devices

SW1:
  hostname: 192.168.3.1
  platform: ios
  username: mcp-access
  password: Aa123456
  groups:
    - cisco_ios
  data:
    role: core_switch

# R2:
#   hostname: 192.168.100.102
#   platform: ios
#   groups:
#     - cisco_ios
#   data:
#     role: core_router

# R3:
#   hostname: 192.168.100.103
#   platform: ios
#   groups:
#     - cisco_ios
#   data:
#     role: core_router